import "./globals.css";
import MainNavbar from "@/components/MainNavbar";
import SessionWrapper from "@/components/SessionWrapper";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';



export const metadata = {
  title: "Quizhub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <body className="bg-gradient-to-b from-gray-100 to-orange-200"> */}
      <body className="text-neutral-800 dark:text-[#e3e3e3]">
        <SessionWrapper>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
        <ToastContainer
                position="top-right"
                autoClose={3000}
                hideProgressBar={false}
                newestOnTop={false}
                closeOnClick
                rtl={false}
                pauseOnFocusLoss
                draggable
                draggablePercent={60}
                pauseOnHover
                theme="light"
                style={{zIndex:100}}
              />
          <div className="min-h-screen bg-gradient-to-br from-slate-50 to-slate-100 dark:from-slate-900 dark:to-slate-800  ">
          {/* <MainNavbar /> */}
      {/* <Suspense fallback={<Loading />}> */}
        {children}
      {/* </Suspense> */}
        </div>
        </ThemeProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
