import "./globals.css";
import Navbar from "@/components/Navbar";
import SessionWrapper from "@/components/SessionWrapper";
import { ThemeProvider } from "next-themes";
import { Suspense } from "react";



export const metadata = {
  title: "Quizhub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* <body className="bg-gradient-to-b from-gray-100 to-orange-200"> */}
      <body className="text-neutral-800 dark:text-[#e3e3e3]">
        <SessionWrapper>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <div className="  2xl:border-x-2 border-gray-300 dark:border-neutral-700">
          <Navbar />
      {/* <Suspense fallback={<Loading />}> */}
        {children}
      {/* </Suspense> */}
        </div>
        </ThemeProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
